-- ==================================================================
-- SCRIPT DE BASE DE DATOS: SISTEMA WARRANTY
-- Motor: PostgreSQL


-- 1. CONFIGURACIÓN DE ENTORNO
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

-- 2. CREACIÓN DE TABLAS

-- Tabla Usuario
CREATE TABLE public.usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    email character varying(100) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    rol character varying(20) NOT NULL
);

-- Tabla Tienda
CREATE TABLE public.tienda (
    id_tienda integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer,
    nombre_tienda character varying(100) NOT NULL,
    direccion character varying(255),
    email character varying(120),
    telefono character varying(30),
    rut_tienda character varying(12) NOT NULL
);

-- Tabla Boleta
CREATE TABLE public.boleta (
    id_boleta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_boleta character varying(50),
    fecha_compra date NOT NULL,
    total integer NOT NULL,
    url_imagen character varying(255),
    nombre_vendedor character varying(100),
    id_usuario integer NOT NULL,
    id_tienda integer
);

-- Tabla Producto
CREATE TABLE public.producto (
    id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto character varying(150) NOT NULL,
    marca character varying(80),
    modelo character varying(80),
    categoria character varying(80),
    sku character varying(60) UNIQUE,
    garantia_meses smallint DEFAULT 0 NOT NULL
);

-- Tabla Detalle Boleta
CREATE TABLE public.detalle_boleta (
    id_detalle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_boleta integer NOT NULL,
    id_producto integer DEFAULT 1 NOT NULL,
    cantidad integer DEFAULT 1 NOT NULL,
    precio_unitario integer NOT NULL,
    CONSTRAINT uq_detalle_boleta_producto UNIQUE (id_boleta, id_producto)
);

-- Tabla Garantia
CREATE TABLE public.garantia (
    id_garantia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio date NOT NULL,
    fecha_termino date NOT NULL,
    estado character varying(20) NOT NULL,
    id_boleta integer NOT NULL,
    CONSTRAINT uq_garantia_boleta UNIQUE (id_boleta)
);

-- Tabla Regla Notificacion
CREATE TABLE public.regla_notificacion (
    id_regla integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_regla character varying(120) NOT NULL,
    dias_previstos integer NOT NULL,
    canal character varying(50) NOT NULL,
    plantilla text NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    id_usuario integer NOT NULL
);

-- Tabla Notificacion
CREATE TABLE public.notificacion (
    id_notificacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_envio timestamp without time zone NOT NULL,
    tipo_notificacion character varying(50) NOT NULL,
    estado character varying(20) DEFAULT 'pendiente'::character varying NOT NULL,
    id_boleta integer,
    id_garantia integer,
    id_regla integer
);

-- Tabla Reclamo
CREATE TABLE public.reclamo (
    id_reclamo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_reclamo date NOT NULL,
    resultado character varying(50) NOT NULL,
    id_detalle integer NOT NULL
);

-- 4. RELACIONES (FOREIGN KEYS)

ALTER TABLE ONLY public.tienda
    ADD CONSTRAINT fk_tienda_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.boleta
    ADD CONSTRAINT fk_boleta_tienda FOREIGN KEY (id_tienda) REFERENCES public.tienda(id_tienda) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.boleta
    ADD CONSTRAINT fk_boleta_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE;

ALTER TABLE ONLY public.detalle_boleta
    ADD CONSTRAINT fk_detalle_boleta FOREIGN KEY (id_boleta) REFERENCES public.boleta(id_boleta) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.detalle_boleta
    ADD CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto) ON UPDATE CASCADE;

ALTER TABLE ONLY public.garantia
    ADD CONSTRAINT fk_garantia_boleta FOREIGN KEY (id_boleta) REFERENCES public.boleta(id_boleta) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.regla_notificacion
    ADD CONSTRAINT fk_regla_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE;

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fk_notif_boleta FOREIGN KEY (id_boleta) REFERENCES public.boleta(id_boleta) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fk_notif_garantia FOREIGN KEY (id_garantia) REFERENCES public.garantia(id_garantia) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fk_notif_regla FOREIGN KEY (id_regla) REFERENCES public.regla_notificacion(id_regla) ON UPDATE CASCADE;

ALTER TABLE ONLY public.reclamo
    ADD CONSTRAINT fk_reclamo_detalle FOREIGN KEY (id_detalle) REFERENCES public.detalle_boleta(id_detalle) ON UPDATE CASCADE ON DELETE CASCADE;